/* Generated by tests/z80/gen_tests.py -- do not edit by hand.
 *
 * The 79 instruction descriptors of ZEXALL, in both of the exerciser's two
 * builds.  See zexall_tests.c for the digest of the assembler file they were
 * read from and the command that rebuilds them; run_z80.sh checks that digest
 * by regenerating whenever docs/ is present.
 */
#ifndef SMS3DO_ZEXALL_TESTS_H
#define SMS3DO_ZEXALL_TESTS_H

/* Four opcode bytes then the sixteen of a MachineState, little endian:
 * memop, iy, ix, hl, de, bc, f, a, sp (zexall.sms.asm:128-147). */
#define ZEX_CASE_BYTES 20

typedef struct
{
  const char    *label;        /* the assembler label, e.g. "cplop" */
  const char    *name;         /* what the exerciser prints, e.g. "cpl" */
  unsigned char  base[ZEX_CASE_BYTES];
  unsigned char  counter[ZEX_CASE_BYTES];
  unsigned char  shifter[ZEX_CASE_BYTES];
  unsigned long  crc;          /* the CRC published for this build */
  unsigned long  stated_cases; /* the case total the ASSEMBLER'S COMMENT
                                * states -- an independent figure, not one
                                * recomputed from the masks beside it */
  unsigned char  fmask;        /* this descriptor's own flag mask */
} zex_test_t;

#define ZEX_TEST_COUNT 79

/* The documented build: flag mask $D7, the first of each pair of published
 * CRCs.  This is the verdict. */
extern const zex_test_t zex_tests_doc[ZEX_TEST_COUNT];

/* The undocumented build: flag mask $FF, the second CRC, and the exerciser's
 * own ordering for that build.  The only thing here that exercises bits 3
 * and 5 of F. */
extern const zex_test_t zex_tests_undoc[ZEX_TEST_COUNT];

#endif /* SMS3DO_ZEXALL_TESTS_H */
