#!/bin/sh
#
# What the console's compiler makes of a file of translated code, in
# ARM instructions and in cycles: the file compiled to assembly by the
# console chain's own compiler with the very options the Makefile hands
# it (the cross compiler, the include path, the optimisation, the
# calling standard), then the instructions counted by kind -- loads,
# stores, multiple loads and stores, everything else -- and priced at
# the measured rate of the ARM60 (a register operation 1.05, a load
# 5.25, a store 6.30 cycles; a multiple load or store priced per
# register moved at the same rates, an upper bound).
#
# One question, before and after: does the direct path to the work RAM
# take loads and stores out of the emitted code, and how many. The same
# ROM's C, generated by the tool before and after a change, gives two
# lines to hold side by side. The count is static -- instructions in the
# file, not instructions run -- which is what a change of form is judged
# on; the runners say what runs.
#
# Not hooked to a make target: it needs the cross compiler under bin/,
# which no host bench touches (tests/memprobe/check_shapes.sh does the
# same for its object dump). Run from the repository root:
#
#   sh tests/z80c/arm_count.sh <rom_code.c>
#
# Prints one line:
#
#   arm: <file> insns=<n> ldr=<n> str=<n> ldm=<n>/<regs> stm=<n>/<regs> branches=<n> cycles=<n>
#
# where ldr and str count single loads and stores (every width and
# condition), ldm and stm the multiple forms and the registers they
# move, branches the B, BL and their conditional forms (priced as
# register operations, which understates them alike on both sides),
# and cycles the sum at the rates above, in whole cycles.
#
set -e

# The file, resolved before the change of directory below.
case "${1:-}" in
  '') echo "usage: sh tests/z80c/arm_count.sh <rom_code.c>"; exit 2;;
  /*) FILE=$1;;
  *)  FILE="$PWD/$1";;
esac
if [ ! -f "$FILE" ]; then
  echo "usage: sh tests/z80c/arm_count.sh <rom_code.c> (no file at $1)"
  exit 2
fi

cd "$(dirname "$0")/../.."

# The devkit, found the way the Makefile finds it: TDO_DEVKIT_PATH,
# else the .devkit-path file, else this directory.
if [ -n "${TDO_DEVKIT_PATH:-}" ]; then
  DEVKIT=${TDO_DEVKIT_PATH%/}
elif [ -f .devkit-path ]; then
  DEVKIT=$(cat .devkit-path)
  DEVKIT=${DEVKIT%/}
else
  DEVKIT=.
fi
ARMCC=$DEVKIT/bin/compiler/linux/armcc
if [ ! -x "$ARMCC" ]; then
  echo "arm_count: no cross compiler at $ARMCC"
  exit 2
fi

# The options of the console build, copied from the Makefile (INCFLAGS,
# DEFFLAGS and CFLAGS of the release build): the include path, the
# release definitions, the optimisation and the target. Copied, not
# read: the Makefile has no target that prints them, and this script
# must not add one. A reader who changes them there changes them here.
INCFLAGS="-I$DEVKIT/include/3do -I$DEVKIT/include/community -I$DEVKIT/include/ttl"
DEFFLAGS="-DNDEBUG=1"
CFLAGS='-O2 -zpno_check_stack -bigend -za1 -zi4 -fa -fh -fx -fpu none -arch 3 -apcs 3/32/nofp/swst/wide/softfp'

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# shellcheck disable=SC2086
"$ARMCC" $INCFLAGS -Isrc $DEFFLAGS $CFLAGS -S "$FILE" -o "$WORK/code.s"

# An instruction is an indented line whose first word is an upper case
# mnemonic; labels stand at the margin, directives (AREA, DCD, EXPORT,
# END...) are told apart by name, and a word that is neither a known
# directive nor a known mnemonic is counted as a register operation AND
# named on stderr, so that a directive this list misses is seen rather
# than swallowed. A multiple transfer names its registers between
# braces, ranges counted by their bounds.
awk -v file="$1" '
  function regs(s,   n, k, parts, i, lo, hi) {
    sub(/^[^{]*\{/, "", s); sub(/\}.*$/, "", s)
    n = split(s, parts, ",")
    k = 0
    for(i = 1; i <= n; i++) {
      if(index(parts[i], "-") > 0) {
        split(parts[i], b, "-")
        lo = regno(b[1]); hi = regno(b[2])
        k += (hi >= lo) ? hi - lo + 1 : 1
      } else
        k++
    }
    return k
  }
  function regno(r) {
    # The APCS names: a1-a4 are r0-r3, v1-v8 are r4-r11, then ip, sp,
    # lr, pc; a plain rN is itself.
    if(r ~ /^r[0-9]+$/) return substr(r, 2) + 0
    if(r ~ /^a[1-4]$/) return substr(r, 2) - 1
    if(r ~ /^v[1-8]$/) return substr(r, 2) + 3
    if(r == "sb") return 9
    if(r == "sl") return 10
    if(r == "fp") return 11
    if(r == "ip") return 12
    if(r == "sp") return 13
    if(r == "lr") return 14
    if(r == "pc") return 15
    return 0
  }
  /^[ \t]+[A-Z][A-Z0-9]*/ {
    m = $1
    if(m ~ /^(AREA|DCD|DCDU|DCB|DCW|DCWU|DCQ|DCI|DCFS|DCFD|EXPORT|IMPORT|EXTERN|GLOBAL|END|DATA|ALIGN|CODE16|CODE32|ARM|THUMB|KEEP|EQU|SPACE|FILL|LTORG|ENTRY|PROC|ENDP|FUNCTION|ENDFUNC|PRESERVE8|REQUIRE8|RN|MACRO|MEND|GBLA|GBLL|GBLS|LCLA|LCLL|LCLS|SETA|SETL|SETS|IF|ELSE|ENDIF|WHILE|WEND|ASSERT|INFO|OPT|TTL|SUBT|GET|INCLUDE|ROUT|ATTR|DN|SN|QN|CN|CP|FN)$/)
      next
    insns++
    if(m ~ /^LDM/) { ldm++; ldm_regs += regs($0); next }
    if(m ~ /^STM/) { stm++; stm_regs += regs($0); next }
    if(m ~ /^LDR/) { ldr++; next }
    if(m ~ /^STR/) { str++; next }
    if(m ~ /^B(L|X)?(EQ|NE|CS|CC|MI|PL|VS|VC|HI|LS|GE|LT|GT|LE|AL|HS|LO)?$/) { br++; next }
    if(m !~ /^(ADD|ADC|SUB|SBC|RSB|RSC|AND|ORR|EOR|BIC|MOV|MVN|CMP|CMN|TST|TEQ|MUL|MLA|UMULL|UMLAL|SMULL|SMLAL|SWP|SWI|MRS|MSR|NOP|LSL|LSR|ASR|ROR|RRX|MRC|MCR|CDP|LDC|STC)/) {
      if(!(m in unknown)) { unknown[m] = 1; printf("arm: unknown mnemonic %s counted as a register operation\n", m) > "/dev/stderr" }
    }
    other++
  }
  END {
    cycles = 1.05 * (other + br) + 5.25 * (ldr + ldm_regs) + 6.30 * (str + stm_regs)
    printf("arm: %s insns=%d ldr=%d str=%d ldm=%d/%d stm=%d/%d branches=%d cycles=%.0f\n",
           file, insns, ldr, str, ldm, ldm_regs, stm, stm_regs, br, cycles)
  }
' "$WORK/code.s"
